### PR TITLE
codegen conditional on hasmethod

### LINKED ISSUE #16: Multiple `@kwcalls` redefines methods causing warnings
https://github.com/JuliaAstro/Transits.jl/pull/23#issuecomment-846185815

Calling `@kwcall` multiple times on the same method name will create warnings in module code. This is happening because https://github.com/cscherrer/KeywordCalls.jl/blob/96b14dc43afc29b7a2299e2001b67985464cfd8e/src/KeywordCalls.jl#L39-L43 adds the two `foo(::NamedTuple)` and `foo(; kwargs...)` calls, regardless if they exist already.

### PR DESCRIPTION
**Pull request by cscherrer**

### CODE REVIEW

**Comment by cscherrer** [comment]
Currently passing everything except precompilation. Here's the error:
```julia
caching with precompilation: Test Failed at /home/chad/git/KeywordCalls/test/runtests.jl:86
  Expression: Precompile2.test() == (a = 2, b = 1)
   Evaluated: (b = 1, a = 2) == (a = 2, b = 1)
Stacktrace:
 [1] macro expansion
   @ ~/git/KeywordCalls/test/runtests.jl:86 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/git/KeywordCalls/test/runtests.jl:86
Test Summary:               | Fail  Total
caching with precompilation |    1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/chad/git/KeywordCalls/test/runtests.jl:85
ERROR: Package KeywordCalls errored during testing
```

**Comment by cscherrer** [comment]
Think it's working, what do you think @mileslucas ?

**Comment by cscherrer** [comment]
Just to be clear, this doesn't yet address #17 , but only #16

**Review by mileslucas — APPROVED** [review]
Looks good to me. The only catch I can think of is the case where someone has defined e.g., `foo(::NamedTuple)` outside of the `@kwcall` macro. Basically `hasmethod` has no way to know who wrote the preceding method. I think that's fair, especially if its pointed out somewhere in the docs.

**Comment by cscherrer** [comment]
Great point, I've updated the docstrings

**Pull request merged**
