### PR TITLE
static_hasmethod tweaks

### PR DESCRIPTION
**Pull request by cscherrer**

### CODE REVIEW

**Comment by cscherrer** [comment]
Hi @mileslucas @icweaver , I was having some issues using KeywordCalls with MeasureTheory where `using MeasureTheory` would give me a few screenfulls of warnings. I managed to fix it here.

One problem is that it's failing tests for contructors with default values. I'll try to find a workaround, but if no one's using it I might consider removing it temporarily. OTOH _functions_ with defaults seem to be fine, and `Breakage` says Transits.jl tests still pass.

**Comment by icweaver** [comment]
Hi @cscherrer, sorry for missing your ping! Thanks for the update, right, things still look to be working alright on our end! Just to make sure I am following the potential issue here, is the problem with just using default values with `@kwstruct`?

**Comment by cscherrer** [comment]
No worries :)

Yeah, so in `runtests.jl`, the setup is
```julia
struct Bar{N,T}
    nt::NamedTuple{N,T}
end

@kwstruct Bar(a,b,c=0)
```

Then
```julia
julia> Bar((a=2,b=3,c=4))
Bar{(:a, :b, :c), Tuple{Int64, Int64, Int64}}((a = 2, b = 3, c = 4))

julia> Bar((a=2,b=3))
Bar{(:a, :b), Tuple{Int64, Int64}}((a = 2, b = 3))
```

so basically defaults don't work with `@kwstruct`. I didn't spend too long trying to get it working, but I don't use this feature anyway and it looked like it wasn't coming up in your library either so I went ahead with it.

**Comment by icweaver** [comment]
Ah, sounds good. Right, I think we're happy to just keep using outer constructors for our use case!

**Pull request merged**
